tt_forum/forum/urls.py
from django.urls import path, re_path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'forum'
urlpatterns = [
        path('', views.index, name='index'),
        path('board/<int:obj_id>/<int:page_id>/', views.board, name='board'),
        path('thread/<int:obj_id>/<int:page_id>/', views.thread, name='thread'),
        path('post/<int:obj_id>', views.post, name='post'),
        path('file/<int:obj_id>', views.file, name='file'),
        path('profile/<int:obj_id>', views.profile, name='profile'),

        path('new_board/', views.new_board, name='new_board'),
        path('new_thread/<int:obj_id>/', views.new_thread, name='new_thread'),
        path('new_post/<int:obj_id>/', views.new_post, name='new_post'),

        path('board_exc/<int:obj_id>/<int:page_id>/', views.board_exc, name='board_exc'),
        path('board_private/<int:obj_id>/<int:page_id>/', views.board_private, name='board_private'),
        path('board_files/<int:obj_id>/<int:page_id>', views.board_files, name='board_files'),
        path('board_delete/<int:obj_id>/', views.board_delete, name='board_delete'),
        path('board_sub/<int:obj_id>/<int:page_id>/', views.board_sub, name='board_sub'),

        path('thread_sticky/<int:obj_id>/<int:page_id>', views.thread_sticky, name='thread_sticky'),
        path('thread_delete/<int:obj_id>/<int:page_id>', views.thread_delete, name='thread_delete'),
        path('thread_lock/<int:obj_id>/<int:page_id>', views.thread_lock, name='thread_lock'),
        path('thread_private/<int:obj_id>/<int:page_id>', views.thread_private, name='thread_private'),
        path('thread_destroy/<int:obj_id>/<int:page_id>/', views.thread_destroy, name='thread_destroy'),
        path('thread_sub/<int:obj_id>/<int:page_id>/', views.thread_sub, name='thread_sub'),

        path('post_sticky/<int:obj_id>/', views.post_sticky, name='post_sticky'),
        path('post_delete/<int:obj_id>/', views.post_delete, name='post_delete'),
        path('post_destroy/<int:obj_id>/<int:page_id>/', views.post_destroy, name='post_destroy'),

        path('profile_own/<int:obj_id>/<int:profile_id>/', views.profile_own, name='profile_own'),
        path('profile_mod/<int:obj_id>/<int:profile_id>/', views.profile_mod, name='profile_mod'),
        path('profile_acc/<int:obj_id>/<int:profile_id>/', views.profile_acc, name='profile_acc'),
        path('profile_ban/<int:obj_id>/<int:profile_id>/', views.profile_ban, name='profile_ban'),

        path('profile_search/', views.profile_search, name='profile_search'),
        path('profile_bulk/<int:obj_id>/<int:page_id>', views.profile_bulk, name='profile_bulk'),

        path('register/', views.register, name='register'),
        path('register_success/', views.register_success, name='register_success'),
        path('my_account/', views.my_account, name='my_account'),

        re_path(r'^confirm_email/(?P<token>[a-z0-9]{64})/$', views.confirm_email, name='confirm_email'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tt_forum/tt_forum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
        path('', include('forum.urls')),
        path('accounts/', include('django.contrib.auth.urls')),
]

tt_forum/forum/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.http import HttpResponse
from django.db import transaction
from django.db.models import Q, F
from django.db.models.functions import Lower
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.conf import settings
from django.template import loader
from math import ceil
from re import findall, search

from .models import Board, Thread, Post, Profile, Attachment

def check_model_perms(obj_type, post=False):
    def dec(fun):
        def inner(request, obj_id, **kwargs):
            obj = get_object_or_404(obj_type.objects.select_related(), pk=obj_id)

            # Get thread and board and profile applicable to object
            th = None
            if not obj_type is Board:
                th = obj
                while not type(th) is Thread:
                    th = th.parent
            br = th.parent if th else obj

            prf = Profile.objects.get(user=request.user) if request.user.is_authenticated else None

            # Check view permissions
            if not prf or not prf.admin:
                if br.private or (th and th.private) or post:
                    if not prf:
                        return redirect("{}?next={}".format(reverse('login'), request.path))
                    if not br.users.filter(pk=prf.pk).exists():
                        raise PermissionDenied

            # Check modify permissions (users without an unconfirmed email
            # address are not allowed to post)
            if post and not prf.admin:
                if br.banned_users.filter(pk=prf.pk).exists() or not prf.user.email:
                    raise PermissionDenied
            return fun(request=request, obj=obj, br=br, prf=prf, **kwargs)
        return inner
    return dec

# Every view that uses check_admin_perms requires atomicity
# and locking of the objects they use so the whole check_admin_perms
# function is made a transaction block and the applicable objects are
# locked with select_for_update
#
# Level 0: admin
# Level 1: board-owner
# Level 2: moderator
def check_admin_perms(obj_type, level):
    def dec(fun):
        @transaction.atomic
        def inner(request, obj_id, **kwargs):
            # User must be authenticated
            if not request.user.is_authenticated:
                return redirect("{}?next={}".format(reverse('login'), request.path))

            # Get obj and applicable board
            prf = Profile.objects.select_related().get(user=request.user)
            obj = get_object_or_404(obj_type.objects.select_related().select_for_update(), pk=obj_id)

            br = obj
            while not type(br) is Board:
                br = br.parent

            # Check permissions level
            ul = 3
            if prf.admin:
                ul = 0
            elif br.owners.filter(pk=prf.pk).exists():
                ul = 1
            elif br.moderators.filter(pk=prf.pk).exists():
                ul = 2

            if ul > level:
                raise PermissionDenied

            return fun(request=request, obj=obj, br=br, prf=prf, level=ul, **kwargs)
        return inner
    return dec

# Level 0: admin
# Level 1: board-owner
# Level 2: moderator
# Level 3: normal-user
# Level 4: not authenticated/no access to board
# Level 5: banned-user
# Level 6: user has no confirmed email
def get_user_level(br, prf):
    level = 3
    if prf is None:
        level = 4
    elif prf.admin:
        level = 0
    elif not prf.user.email:
        level = 6
    elif br.owners.filter(pk=prf.pk).exists():
        level = 1
    elif br.moderators.filter(pk=prf.pk).exists():
        level = 2
    elif br.banned_users.filter(pk=prf.pk).exists():
        level = 5
    elif not br.users.filter(pk=prf.pk).exists():
        level = 4
    return level

def send_confirm_email(prf, req):
    tpl = loader.get_template('forum/email/confirm_email.html')
    context = { 'token' : prf.gen_token() }
    send_mail(
            subject='Please confirm your COS Forum email address',
            html_message=tpl.render(context, req),
            from_email='no-reply@cosforum.com',
            recipient_list=[prf.new_em],
            message='')

def paginate(request, objs, page_id):
    pp = request.session.get('objs_pp', 10)
    page = Paginator(objs, pp)
    if not 1 <= page_id <= page.num_pages:
        page_id = page.num_pages
    return (page.page(page_id), page_id, page.num_pages)

def validate_pword(pword):
    if getattr(settings, "DEBUG_PWORD", False):
        return None
    if len(pword) < 8:
        return "len"
    if not search(r'[a-z]', pword):
        return "lower"
    if not search(r'[A-Z]', pword):
        return "upper"
    if not search(r'[0-9]', pword):
        return "number"
    if not search(r'[^a-zA-Z0-9]', pword):
        return "special"
    return None

def index(request):
    br = None
    prf = None
    if not request.user.is_authenticated:
        br = Board.objects.filter(private=False)
    else:
        prf = request.user.profile
        if not prf.admin:
            br = Board.objects.filter(Q(private=False) | Q(exclusive=False) |
                    Q(users=prf)).distinct()
        else:
            br = Board.objects.all()
    br = br.order_by(Lower('name'))
    context = { 'boards': br, 'profile' : prf }
    return render(request, 'forum/index.html', context)

@check_model_perms(Board)
def board(request, obj, prf, page_id, **kwargs):
    level = get_user_level(obj, prf)

    # If board is not exclusive and user does not have access, add user
    if level == 4 and prf and not obj.exclusive:
        obj.users.add(prf)
        level = 3

    args = {}
    if level > 2:
        args['deleted'] = False
        if level > 3:
            args['private'] = False

    th = obj.children.filter(**args).order_by('-sticky', '-last')
    th, page_id, max_pages = paginate(request, th, page_id)

    subbed = obj.subbed_users.filter(pk=prf.id).exists() if prf else False

    context = {
            'board' : obj,
            'threads' : th,
            'page_id' : page_id,
            'page_max' : max_pages,
            'level' : level,
            'subbed' : subbed
            }
    return render(request, 'forum/board.html', context)

@check_model_perms(Thread)
def thread(request, obj, br, prf, page_id, **kwargs):
    level = get_user_level(br, prf)
    if obj.deleted and level > 2:
        raise PermissionDenied

    posts = obj.children.all().prefetch_related().order_by('-sticky', 'time')
    posts, page_id, max_pages = paginate(request, posts, page_id)
    context = {
            'board' : br,
            'thread' : obj,
            'posts' : posts,
            'page_id' : page_id,
            'page_max' : max_pages,
            'level' : level
            }
    return render(request, 'forum/thread.html', context)

def post(request, obj_id):
    pst = get_object_or_404(Post.objects.select_related(), pk=obj_id)
    st = pst.parent.children.all().order_by('-sticky', 'time')
    pos = ceil((list(st).index(pst) + 1) / int(request.session.get('objs_pp', 10)))

    return redirect(reverse('forum:thread', args=(pst.parent.id, pos)) +
            "#post_" + str(pst.id))

# sendfile can be used to optimise serving of files
@check_model_perms(Attachment)
def file(request, obj, br, prf, **kwargs):
    if (obj.parent.parent.deleted or obj.parent.deleted) \
            and get_user_level(br, prf) > 2:
                raise PermissionDenied

    # For testing purposes
    if not obj.attachment:
        return HttpResponse("No file")
    import magic
    ft = magic.from_file("{}/{}".format(settings.ATTACHMENT_ROOT, obj.attachment.name), mime=True)
    response = HttpResponse(obj.attachment.file, content_type=ft)
    response['Content-Disposition'] = 'attachment; filename="{}"'.format(obj.name)
    return response

@login_required
def profile(request, obj_id):
    cur_prf = Profile.objects.get(user=request.user)
    prf = get_object_or_404(Profile, pk=obj_id)

    own = Profile.objects.none()
    mod = own

    if cur_prf.admin:
        own = Board.objects.all()
    else:
        own = cur_prf.owned_boards.all()
        mod = cur_prf.mod_boards.all()

    cmb = (own | mod).distinct().order_by(Lower('name'))
    if not cmb:
        raise PermissionDenied

    boards = []
    for b in cmb:
        bn = b.banned_users.filter(pk=prf.id).exists()
        o = not bn and b.owners.filter(pk=prf.id).exists()
        m = not bn and (o or b.moderators.filter(pk=prf.id).exists())
        a = not bn and (o or m or not b.exclusive or b.users.filter(pk=prf.id).exists())
        cown = b in own
        boards.append({
                'id' : b.id,
                'name' : b.name,
                'exc' : b.exclusive,
                'own' : o,
                'mod' : m,
                'acc' : a,
                'ban' : bn,
                'cown' : cown
                })

    context = {
            'boards' : boards,
            'profile' : prf,
            'cur_prf' : cur_prf
            }
    return render(request, 'forum/profile.html', context)

@login_required
def new_board(request):
    prf = Profile.objects.get(user=request.user)
    if not prf.admin:
        raise PermissionDenied

    name = request.POST.get('name', '').strip()
    if not name:
        raise PermissionDenied

    Board.objects.create(name=name)

    return redirect(reverse('forum:index'))

@check_model_perms(Board, post=True)
def new_thread(request, obj, prf, **kwargs):
    title = request.POST.get('title', '').strip();
    text = request.POST.get('text', '').rstrip();
    if not text or not title:
        raise PermissionDenied

    prf.posts = F('posts') + 1
    prf.save()

tt_forum/forum/templates/forum/board.html
{% extends "forum/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "forum/css/board.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "forum/css/lst_tbl.css" %}">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<title>{{ board.name }} - COS Forum</title>

{% endblock %}
{% block onready %}
<script>
nav_level("{{ board.name }}", "{% url 'forum:board' board.id 1 %}");
set_pages({{ page_id }}, {{ page_max }})

function show_new_thread() {
	a = document.getElementById("board_new_thread");
	a.style.display = a.style.display == '' ? 'block' : '';
	b = document.getElementById("board_new_thread_open");
	b.innerHTML = a.style.display != '' ? 'Close' : 'New Thread';
	t = document.getElementById("lst_tbl");
	if (t != null) {
		t.style.display = a.style.display != '' ? 'none' : 'table';
	}
	n = document.getElementById("board_user_mng_cnt")
	if (n != null) {
		n.style.display = '';
	}
	ns = document.getElementsByClassName("no_content");
	for (var i = 0; i < ns.length; i++) {
		ns[i].style.display = a.style.display != '' ? 'none' : '';
	}
}

function show_user_mng() {
	if (document.getElementById("board_new_thread").style.display != '') {
		show_new_thread()
	}
	m = document.getElementById("board_user_mng_cnt");
	m.style.display = m.style.display == '' ? 'table' : '';
}

function confirm_exc() {
	v = document.getElementById("board_confirm_box");
	v.style.display = v.style.display != 'block' ? 'block' : 'none';
}

var simplemde = new SimpleMDE({
	element: document.getElementById("board_new_thread_txt"),
	forceSync: true,
	spellChecker: false,
	hideIcons: ["quote", "guide", "preview", "side-by-side"],
	tabSize: 4,
	status: false,
});

</script>
{% endblock %}
{% block content %}
{% if level <= 1 %}
<div id=board_confirm_box>
	<div id=board_confirm_box_btns>
		Are you sure you want to change this board's exclusivity? If the board is made
		non-exclusive all private threads will be reset to public.

		<a href="{% url 'forum:board_exc' board.id page_id %}" id=board_confirm_yes>Yes</a>
		<a href="javascript:confirm_exc()" id=board_confirm_no>No</a>
	</div>
</div>
{% endif %}

{% if level <= 3 %}
<div id="board_top_bar">
	<a id=board_new_thread_open class="btn board_top_btns"
		href="javascript:show_new_thread()">New Thread</a>

	<a class="btn board_top_btns" href="{% url 'forum:board_sub' board.id page_id %}">
		{% if subbed %}
		Unsubscribe
		{% else %}
		Subscribe
		{% endif %}
	</a>

	{% if level <= 2 %}
	<br>
	<a class="btn board_top_btns" href="javascript:show_user_mng()">User management</a>
	{% endif %}

	{% if level <= 1 %}
	<span id="board_admin_label">
		Make board
	</span>
	<a class="btn board_top_btns" href="javascript:confirm_exc()">
		{% if board.exclusive %}
		Non-Exclusive
		{% else %}
		Exclusive
		{% endif %}
	</a>
	{% if board.exclusive %}
	<a class="btn board_top_btns" href="{% url 'forum:board_private' board.id page_id %}">
		{% if board.private %}
		Public
		{% else %}
		Private
		{% endif %}
	</a>
	{% endif %}
	<a class="btn board_top_btns" href="{% url 'forum:board_files' board.id page_id %}">
		{% if board.allow_files %}
		Block files
		{% else %}
		Allow files
		{% endif %}
	</a>
	{% endif %}
</div>

<div id=board_new_thread>
		<form action="{% url 'forum:new_thread' board.id %}" method="post">
			{% csrf_token %}
			<label for=board_new_thread_ttl id=board_new_thread_lbl>Thread title:</label>
			<input name=title type=text id=board_new_thread_ttl
				placeholder="Enter title for new thread" required />
			<button type=submit class=btn id=board_new_thread_btn>Create thread</button>
			<div class=mono id=board_new_thread_cnt>
				<textarea name=text id=board_new_thread_txt required></textarea>
			</div>
		</form>
</div>

{% if level <= 2 %}
<div id=board_user_mng_cnt>
	<div id=board_user_search_cnt>
		<p class=board_user_info>You can search for a user from
		this form. You will be taken to their profile management page
		once they are found</p>
		<hr>

		<div style="width: 70%; margin-left: 15%; margin-top: 5%;">
			<form action="{% url 'forum:profile_search' %}" method=post>
				{% csrf_token %}
				<label for=board_user_search_username>Username:</label>
				<input type=text name=username id=board_user_search_username required />
				<button class=btn id=board_user_search_btn>Search</button>
			</form>
		</div>
	</div>

	<div style="display: table-cell; width: 1%;"></div>

	<div id=board_bulk_users>
		<p class=board_user_info>You can manage users in bulk from this form. Any non-existing
		users will be ignored. Users with a higher level than the one specified below will
		be demoted to the specified level.</p>
		<hr>

		<form action="{% url 'forum:profile_bulk' board.id page_id %}" method=post enctype="multipart/form-data">
			{% csrf_token %}

			<div id=board_bulk_file_cnt>
				<label id=board_bulk_file_label for=board_bulk_file>CSV upload:</label>
				<input type=file name=csv id=board_bulk_file required />
				<button class=btn id=board_bulk_btn>Upload</button>
			</div>

			<div id=board_bulk_options>
				Change users to permissions level:<br>
				{% if board.exclusive %}
				<input type=radio name=level value=4 required>No access</input><br>
				<input type=radio name=level value=3 required>Access</input><br>
				{% endif %}
				{% if level <= 1 %}
				<input type=radio name=level value=2 required>Moderator</input><br>
				{% endif %}
				{% if level == 0 %}
				<input type=radio name=level value=1 required>Owner</input><br>
				{% endif %}
			</div>

		</form>
	</div>
</div>
{% endif %}

{% endif %}

{% if threads %}
<table id=lst_tbl>
	<tr>
		<th style="width: 70%">Title</th>
		<th>Posts</th>
		<th>Last</th>
	</tr>

	{% for thread in threads %}
	<tr>
		<td>
			{% if thread.locked %}
			<img class=in_svg src="{% static "forum/images/lock.svg" %}">
			{% endif %}
			{% if thread.sticky %}
			<img class=in_svg src="{% static "forum/images/pin.svg" %}">
			{% endif %}

			<a style="color:black" href="{% url 'forum:thread' thread.id 1 %}">
				{{ thread.title }}
				{% if thread.private %}
				<span style="color:red">(PRIVATE)</span>
				{% endif %}
			</a>

			{% if level <= 3 %}
			<a class="lst_tbl_btn btn" href="{% url 'forum:thread_sub' thread.id page_id %}">
				{% if thread in user.profile.sub_threads.all %}
				Unsubscribe
				{% else %}
				Subscribe
				{% endif %}
			</a>
			{% endif %}

			{% if level <= 2 %}
			<a class="lst_tbl_btn btn" href="{% url 'forum:thread_delete' thread.id page_id %}">
				{% if thread.deleted %}
				Un-delete
				{% else %}
				Delete
				{% endif %}
			</a>
			<a class="lst_tbl_btn btn" href="{% url 'forum:thread_sticky' thread.id page_id %}">
				{% if thread.sticky %}
				Un-sticky
				{% else %}
				Sticky
				{% endif %}
			</a>
			<a class="lst_tbl_btn btn" href="{% url 'forum:thread_lock' thread.id page_id %}">
				{% if thread.locked %}
				Unlock
				{% else %}
				Lock
				{% endif %}
			</a>
			{% if board.exclusive %}
			<a class="lst_tbl_btn btn" href="{% url 'forum:thread_private' thread.id page_id %}">
				{% if thread.private %}
				Public
				{% else %}
				Private
				{% endif %}
			</a>
			{% endif %}
			{% if level == 0 %}
			<a class="lst_tbl_btn btn" href="{% url 'forum:thread_destroy' thread.id page_id %}">
				Destroy
			</a>
			{% endif %}
			{% endif %}
		</td>
		<td>{{ thread.children.count }}</td>
		<td>{{ thread.last }}</td>
	</tr>
	{% endfor %}
</table>
{% else %}
<div class=no_content>There are currently no threads available</div>
{% endif %}
{% endblock %}

tt_forum/forum/templates/forum/confirm_success.html
{% extends "registration/base.html" %}
{% block content %}
<div id=acc_main>
	{% if success %}
	<div id=acc_suc>
		Your email address has been successfully confirmed.
	</div>
	{% else %}
	<div id=acc_error>
		This token is invalid
	</div>
	{% endif %}

	<a href="{% url 'forum:index' %}" class=acc_btn>Go to index</a>
	<a href="{% url 'forum:my_account' %}" class=acc_btn>Go to my account</a>
</div>
{% endblock %}

tt_forum/forum/templates/forum/index.html
{% extends "forum/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "forum/css/index.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "forum/css/lst_tbl.css" %}">

<title>COS Forum</title>
{% endblock %}
{% block onready %}
{% if profile.admin %}
	<script>
function show_new_board() {
	c = document.getElementById("index_new_board");
	c.style.display = c.style.display == '' ? 'block' : '';
}
	</script>
{% endif %}
{% endblock %}
{% block content %}
{% if profile.admin %}
<div id=index_top_btns>
	<button onclick="show_new_board()" class=btn id=index_new_board_btn>New board</button>
</div>

<div id=index_new_board>
	<form action="{% url 'forum:new_board' %}" method="post">
		{% csrf_token %}

		<label id=index_new_board_name_lbl for=index_new_board_name>Enter new board name:</label>
		<input type=text name=name id=index_new_board_name placeholder="Enter name here" required />
		<button class=btn id=index_new_board_create>Create board</button>
	</form>
</div>
{% endif %}
{% if boards %}
<table id=lst_tbl>
	<tr>
		<th style="width: 80%">Title</th>
		<th>Last post</th>
	</tr>
	{% for board in boards %}
	<tr>
		<td><a style="color:black"
				href="{% url 'forum:board' board.id 1 %}">{{ board.name }}
				{% if board.private %}
				<span style="color: red">(PRIVATE)</span>
				{% endif %}
			</a>

			{% if profile.admin %}
			<a class="btn lst_tbl_btn" href="{% url 'forum:board_delete' board.id %}">Delete</a>
			{% endif %}

		</td>
		<td>{{ board.last }}</td>
	</tr>
	{% endfor %}
</table>
{% else %}
<div class=no_content>There are currently no boards available</div>
{% endif %}
{% endblock %}

tt_forum/forum/templates/forum/profile.html
{% extends 'forum/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "forum/css/profile.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "forum/css/lst_tbl.css" %}">
{% endblock %}
{% block content %}
<div id=profile_main_cnt>
	<div id=profile_info>
		{% if profile.prf_pic %}
		<img id=profile_ppic src="{{ profile.prf_pic.url }}">
		{% endif %}
		{{ profile.user.username }}<br>
		Posts: {{ profile.posts }}<br>
	</div>
	<div id=profile_boards>
		{% if profile.admin %}
		<div class=no_content>This user has an admin account</div>
		{% else %}
		<p id=profile_inst>Click on a button to change the user's permission level for a board</p>
		<table id=lst_tbl>
			<tr>
				<th>Boards</th>
				{% if cur_prf.admin %}
				<th style="width: 15%; text-align: center;">Owner</th>
				{% endif %}
				<th style="width: 15%; text-align: center;">Moderator</th>
				<th style="width: 15%; text-align: center;">Access</th>
				<th style="width: 15%; text-align: center;">Banned</th>
			</tr>

			{% for board in boards %}
			<tr>
				<td>
					{{ board.name }}
				</td>

				{% if cur_prf.admin %}
				<td class=profile_options>
					<a style="width: 100%" href="{% url 'forum:profile_own' board.id profile.id %}"
							class="lst_tbl_btn btn
						profile_{% if board.own %}positive{% else %}negative{% endif %}">
					{% if board.own %}
					Yes
					{% else %}
					No
					{% endif %}
					</a>
				</td>
				{% endif %}

				<td class=profile_options>
					{% if not board.own %}
					{% if board.cown %}
					<a style="width: 100%" href="{% url 'forum:profile_mod' board.id profile.id %}"
							class="lst_tbl_btn btn
						profile_{% if board.mod %}positive{% else %}negative{% endif %}" >
						{% endif %}
						{% if board.mod %}
						Yes
						{% else %}
						No
						{% endif %}
						{% if board.cown %}
					</a>
					{% endif %}
					{% else %}
					Yes
					{% endif %}
				</td>

				<td class=profile_options>
					{% if board.own or board.mod or not board.exc %}
					Yes
					{% else %}
					<a style="width: 100%" href="{% url 'forum:profile_acc' board.id profile.id %}"
							class="lst_tbl_btn btn
						profile_{% if board.acc %}positive{% else %}negative{% endif %}">
						{% if board.acc %}
						Yes
						{% else %}
						No
						{% endif %}
					</a>
					{% endif %}
				</td>

				<td class=profile_options>
					<a style="width: 100%" href="{% url 'forum:profile_ban' board.id profile.id %}"
							class="lst_tbl_btn btn
						profile_{% if board.ban %}positive{% else %}negative{% endif %}">
						{% if board.ban %}
						Yes
						{% else %}
						No
						{% endif %}
					</a>
				</td>
			</tr>
			{% endfor %}
		</table>
		{% endif %}
	</div>
</div>
{% endblock %}